### ISSUE TITLE
import json instead of using simplejson

### ISSUE THREAD

**Issue by Natim** [Cornices/cornice#418] opened 2016-10-28 09:34 UTC
As far as I know `simplejson` is a drop-in replacement for json which ships in Python2.6+ and Python3.0+

Maybe we could import `json` directly instead?

**Comment by Natim** [comment] 2016-10-28 09:38
Actually no: ``json.dumps({"toto": 1}, use_decimal=True)``

    TypeError: __init__() got an unexpected keyword argument 'use_decimal'

**Comment by leplatrem** [comment] 2016-10-28 09:51
http://stackoverflow.com/a/1960649/141895

**Comment by okin** [comment] 2018-10-03 21:11
I tried to tackle this today because another package I try to port to Python 3 relies on cornice.

I found out that removing the use of `use_decimal` in `cornice.util` does not affect the tests at all.
Unfortunately this doesn't mean that simply switching out the modules is all it takes.

To further tackle this I implemented a custom encoder that decodes byte. Without this there would be some errors on Python 3.4 & 3.5 because this versions won't convert bytes to JSON (but 3.6+ will).
Now I have the tests running on Python 3 but I miss coverage on Python 2.

I'm not so sure how to tackle this. Maybe another test?
If someone wants to help the current (WIP) code is at [here](https://github.com/okin/cornice/tree/feature/drop_simplejson_replacing_with_customencoder).
Any help is appreciated!

**Comment by leplatrem** [comment] 2018-10-04 08:57
Thanks @okin for your investigations!

> I found out that removing the use of use_decimal in cornice.util does not affect the tests at all.

Ok that's bad, we should have a test that asserts the expected behavior. If we decide to drop it, we need to have a very clear upgrade path in the upgrade notes

> ...but I miss coverage on Python 2.

Adding another test is rarely a bad idea ;) 

But to be honest, I would be glad if we dropped Python 2 support. I would even say: «yeah, please do it and bump a major version of cornice».

**Comment by SharpEdgeMarshall** [comment] 2020-03-31 11:01
Any news here?

**Comment by leplatrem** [comment] 2020-03-31 11:03
Let's do it!

**Comment by devilicecream** [comment] 2020-04-01 14:49
I could take this one if it's ok for you guys!

**Comment by devilicecream** [comment] 2020-04-22 17:27
Added myself to the contributors, but besides that I think we can close this issue! @leplatrem

**Closed** 2020-04-24 08:59 UTC
Labels: easy

**Comment by devilicecream** [comment] 2020-04-27 16:46
@leplatrem just realized it may be useful to add this changes in the changelog file as well
